server:
  port: ${port:${PORT:8762}}
management:
  security:
    enabled: false # spring-boot 1.5.2之后严格执行安全策略，所以需要配置这个为false ,否则很多点监控不到
  port: 10177
eureka:
  instance:
    hostname: eureka2
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: 'http://eureka1:8763/eureka/'
    fetch-registry: true
    register-with-eureka: true
  server:
#    enable-self-preservation: false           # 关闭自我保护模式（缺省为打开）
#    eviction-interval-timer-in-ms: 5000       # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    renewal-percent-threshold: '0.8'
spring:
  application:
    name: 'eureka'
    boot:
      admin:
        url: http://localhost:8888
info:  #定义各种额外的详情给springbootadmin服务端显示
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"