server:
  port: ${port:${PORT:8763}}
management:
  security:
    enabled: false # spring-boot 1.5.2之后严格执行安全策略，所以需要配置这个为false ,否则很多点监控不到
  port: 9274
eureka:
  instance:
    hostname: eureka1
    prefer-ip-address: false #true使用IP注册
    leaseRenewalIntervalInSeconds: 10  #eureka client发送心跳给server端的频率,默认30秒
#    lease-expiration-duration-in-seconds: 30 #eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。默认为90秒
  client:
    registryFetchIntervalSeconds: 5 #eureka client间隔多久去拉取服务注册信息，默认为30秒
    service-url:
      defaultZone: 'http://eureka2:8762/eureka/'
    fetch-registry: true
    register-with-eureka: true
  server:
#    enable-self-preservation: false           # 关闭自我保护模式（缺省为打开）
#    eviction-interval-timer-in-ms: 5000       # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    renewal-percent-threshold: '0.8'
spring:
  application:
    name: 'eureka'
    boot:
      admin:
        url: http://localhost:8888
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"